

</div>
<!-- Main Content Block  - END-->


<!-- Footer block - START-->
<div id="footer-block">
    <span class="middle-text-footer"><strong>Author <a href="https://github.com/suvreal" target="_blank" title="Krudo author">&copy;SVRL</a></strong></span>
</div>
<!-- Footer block - END-->


<!-- Javascript initialization - START-->
<script type="module" src="<?php echo constant("APP_ROOT");?>/Assets/JS/main.js"></script>
<!-- Javascript initialization - END-->


</body>


</html>

