

<!-- Box headers - START -->
<h2><span class="material-icons" title="search records">search</span>My products</h2>
<button id="add-product" title="add product"><a href="/product"><span class="material-icons" title="add new product">add</span>Add product</a></button>
<!-- Box headers - END -->


<!-- Products search - START -->
<div id="search-box">
    <input id="searchInput" type="text" name="searchProducts" class="singleInputs" placeholder="Search in products ..." title="Write at least 3 characters">
</div>
<!-- Products search - END -->


<!-- Products blocks - START -->
<div class="content-box">
    <table id="product-data-list" class="data-list">
        <tbody id="data-records">
            <?php $products = $this->Controller->getAllProducts(); ?>
            <?php if (is_array($products) && count($products) > 0) : ?>

                <tr class="data-list-item main-content-record">
                    <th class="data-list-item-element">Title</th>
                    <th class="data-list-item-element">Discount Price</th>
                    <th class="data-list-item-element">Price</th>
                    <th class="data-list-item-element">Controls</th>
                </tr>

                <?php foreach ($products as $product) : ?>
                    <tr class="data-list-item products-box main-content-record">
                        <td class="data-list-item-element initial-products"><?php echo htmlspecialchars($product->getAttributeValue("Title")) ?></td>
                        <td class="data-list-item-element initial-products"><?php echo htmlspecialchars($product->getAttributeValue("DiscountPrice")) ?></td>
                        <td class="data-list-item-element initial-products"><?php echo htmlspecialchars($product->getAttributeValue("Price")) ?></td>
                        <td class="data-list-item-element initial-products">
                            <a href="/product?ID=<?php echo ($product->getId()); ?>"><span class="material-icons" title="edit record">edit_note</span></a>
                            <a href="/product-delete?ID=<?php echo ($product->getId()); ?>"><span class="material-icons" title="delete record">delete</span>
                        </td>
                    </tr>
                <?php endforeach; ?>

            <?php endif; ?>
        </tbody>
    </table>
</div>
<!-- Products blocks - END -->

