<h2>My product XYZ</h2>



<?php
/*
<div class="test">

</div>


$this->getPathName();
var_export($this->Controller->Product);
*/

var_export($this->Controller->Product->getAttributeValues());
?>

<style>
    div.test{
        margin:auto;
        width: 85%;
        min-height: 500px;
        background-color:white;
        border-radius:2px;
        box-shadow:0px 2px 6px #00000063;
    }
</style>