

<!-- Box headers - START -->
<h3 class="center color-black general-return-upper-block">
    <a href="/products" title="back to products">
        <span class="material-icons" >arrow_back</span> Back to products
    </a>
</h3>
<!-- Box headers - END -->


<!-- Box product state - START -->
<?php if ($this->Controller->Product->getId() == 0) : ?>
    <h2 class="center">New product</h2>
<?php else : ?>
    <h2 class="center"><?php echo htmlspecialchars($this->Controller->Product->getAttributeValue("Title")) ?></h2>
<?php endif; ?>
<!-- Box product state - END -->


<!-- Result message - START -->
<?php if (!is_null($this->Controller->ResultMessageState)) : ?>
    <div class="user-message">
        <h3 class="user-message-title"><?php echo ($this->Controller->ResultMessage["title"]); ?></h3>
        <span class="user-message-content"><?php echo ($this->Controller->ResultMessage["content"]); ?></span>
    </div>
<?php endif; ?>
<!-- Result message - END -->

<!-- Product edit/create form - START -->
<form action="/product" method="post" id="product-form">
    <!-- Hidden element for identification check -->
    <input id="productID" name="ID" type="number" value="<?php echo htmlspecialchars($this->Controller->Product->getId()) ?>" hidden>
    <!-- Title element attribute -->
    <label for="productTitle">Title:</label>
    <input id="productTitle" name="Title" type="text" placeholder="My product" value="<?php echo htmlspecialchars($this->Controller->Product->getAttributeValue("Title")) ?>" required>
    <!-- Short Description element attribute -->
    <label for="productShortDesc">Short Description:</label>
    <input id="productShortDesc" name="ShortDescription" type="text" value="<?php echo htmlspecialchars($this->Controller->Product->getAttributeValue("ShortDescription")) ?>" placeholder="interesting, green, blue ..." required>
    <!-- Description element attribute -->
    <label for="productDesc">Description:</label>
    <input id="productDesc" name="Description" type="text" placeholder="what does provide my product, what it is usable for" value="<?php echo htmlspecialchars($this->Controller->Product->getAttributeValue("Description")) ?>" required>
    <!-- Price element attribute -->
    <label for="productPrice">Price:</label>
    <input id="productPrice" name="Price" type="number" value="<?php echo htmlspecialchars($this->Controller->Product->getAttributeValue("Price")) ?>" placeholder="1355" required>
    <!-- Discount price element attribute -->
    <label for="productDiscountPrice">Discount product:</label>
    <input id="productDiscountPrice" name="DiscountPrice" type="number" value="<?php echo htmlspecialchars($this->Controller->Product->getAttributeValue("DiscountPrice")) ?>" placeholder="1699" required>
    <!-- Element differ state edit/create submit -->
    <?php if ($this->Controller->Product->getId() == 0) : ?>
        <button>Save</button>
    <?php else : ?>
        <button>Update</button>
    <?php endif; ?>
</form>
<!-- Product edit/create form - END -->